/*
 * Automatically generated header file, don't edit!
 */
#define ELBOX_HAVE_DOT_CONFIG 1
#define ELBOX_FIRMWARE_VERSION "2.10"
#define ELBOX_FIRMWARE_REVISION "b01"
#define ELBOX_FIRMWARE_REGION "ACT"
#undef  ELBOX_DEBUG
#undef  ELBOX_TWO_LEVEL_ACCOUNT

/* Device Configuration */
#define ELBOX_FIRMWARE_SIGNATURE "N/A"
#define ELBOX_SUPPORT_REALTEK_FW 1
#undef  ELBOX_BOARD_DEFAULT
#undef  ELBOX_BOARD_WMXRG01E
#undef  ELBOX_BOARD_WMXRG02E
#undef  ELBOX_BOARD_WMXCO02E
#undef  ELBOX_BOARD_WAPG14
#undef  ELBOX_BOARD_WAPG18
#undef  ELBOX_BOARD_WAPN03
#undef  ELBOX_BOARD_WAPN06
#undef  ELBOX_BOARD_WAPN07
#undef  ELBOX_BOARD_WAPN09
#undef  ELBOX_BOARD_WAPN10
#undef  ELBOX_BOARD_WAPN15
#undef  ELBOX_BOARD_AP1525
#undef  ELBOX_BOARD_WAPN22
#undef  ELBOX_BOARD_WAPND01
#undef  ELBOX_BOARD_WAPND02
#undef  ELBOX_BOARD_WAPND03
#undef  ELBOX_BOARD_WAPND03CM
#undef  ELBOX_BOARD_WAPN08
#undef  ELBOX_BOARD_WAPN11
#undef  ELBOX_BOARD_WAPN11H
#undef  ELBOX_BOARD_WAPN18
#undef  ELBOX_BOARD_WAPN12
#undef  ELBOX_BOARD_WAPND04
#undef  ELBOX_BOARD_WAPND04CM
#undef  ELBOX_BOARD_WAPND06
#undef  ELBOX_BOARD_WAPND09
#undef  ELBOX_BOARD_WAPND14
#undef  ELBOX_BOARD_WAPND15
#undef  ELBOX_BOARD_WAPND16
#undef  ELBOX_BOARD_WAPND17
#undef  ELBOX_BOARD_WAPND18
#undef  ELBOX_BOARD_WAPND19
#undef  ELBOX_BOARD_WAPAC02
#undef  ELBOX_BOARD_WAPAC09
#undef  ELBOX_BOARD_WAPND27
#undef  ELBOX_BOARD_WAPAC11
#undef  ELBOX_BOARD_WAPN24
#undef  ELBOX_BOARD_WAPN25
#undef  ELBOX_BOARD_WAPAC04
#undef  ELBOX_BOARD_RG12
#undef  ELBOX_BOARD_RG13
#undef  ELBOX_BOARD_WRGG14
#undef  ELBOX_BOARD_WRGG14C
#undef  ELBOX_BOARD_WRGG15C
#undef  ELBOX_BOARD_WRGG16
#undef  ELBOX_BOARD_WRGG19
#undef  ELBOX_BOARD_WRGG19_C
#undef  ELBOX_BOARD_WRGG19_C_ART
#undef  ELBOX_BOARD_WRGG19_C_HSPOT
#undef  ELBOX_BOARD_WRGG22
#undef  ELBOX_BOARD_WRGG23
#undef  ELBOX_BOARD_WRGG24
#undef  ELBOX_BOARD_WRGG27
#undef  ELBOX_BOARD_WRGG27HP
#undef  ELBOX_BOARD_WRGG27_3G
#undef  ELBOX_BOARD_RT3052
#undef  ELBOX_BOARD_WRGN06
#undef  ELBOX_BOARD_WRGN06C
#undef  ELBOX_BOARD_WRGN09
#undef  ELBOX_BOARD_WRGN10
#undef  ELBOX_BOARD_WRGN13
#undef  ELBOX_BOARD_WRGN15
#undef  ELBOX_BOARD_WRGN15C
#undef  ELBOX_BOARD_WRGN16
#undef  ELBOX_BOARD_WRGN16A
#undef  ELBOX_BOARD_WRGN18
#undef  ELBOX_BOARD_WRGN18N
#undef  ELBOX_BOARD_SWRGN18
#undef  ELBOX_BOARD_WRGN19
#undef  ELBOX_BOARD_WRGN20
#undef  ELBOX_BOARD_WRGN22
#undef  ELBOX_BOARD_WRGN22S
#undef  ELBOX_BOARD_WRGN23
#undef  ELBOX_BOARD_WRGN23I
#undef  ELBOX_BOARD_WRGN23TD
#undef  ELBOX_BOARD_WRGN23HA
#undef  ELBOX_BOARD_WRGN27
#undef  ELBOX_BOARD_WRGN27U
#undef  ELBOX_BOARD_WRGN28
#undef  ELBOX_BOARD_WRGN45P
#undef  ELBOX_BOARD_WRGN29
#undef  ELBOX_BOARD_WRGN34
#undef  ELBOX_BOARD_WRGN37
#undef  ELBOX_BOARD_WRGN38
#undef  ELBOX_BOARD_WRGN39
#undef  ELBOX_BOARD_WRGN49
#undef  ELBOX_BOARD_WRGN50
#undef  ELBOX_BOARD_WRGN51
#undef  ELBOX_BOARD_WRGN52
#undef  ELBOX_BOARD_WRGN59
#undef  ELBOX_BOARD_WRGN62
#undef  ELBOX_BOARD_WRGN70
#undef  ELBOX_BOARD_WRGN77
#undef  ELBOX_BOARD_WRGN78
#undef  ELBOX_BOARD_WRGN79
#undef  ELBOX_BOARD_WRGN80
#undef  ELBOX_BOARD_WRGN81
#undef  ELBOX_BOARD_WRGN82
#undef  ELBOX_BOARD_WRGN83
#undef  ELBOX_BOARD_WRGN85
#undef  ELBOX_BOARD_WRGN88E
#undef  ELBOX_BOARD_WRGND02
#undef  ELBOX_BOARD_WRGND03
#undef  ELBOX_BOARD_WRGND04
#undef  ELBOX_BOARD_WRGND06
#undef  ELBOX_BOARD_WRGND12
#undef  ELBOX_BOARD_WRGND21
#undef  ELBOX_BOARD_WRGND23
#undef  ELBOX_BOARD_WRGND24
#undef  ELBOX_BOARD_WRGND07
#undef  ELBOX_BOARD_WRGN42P
#undef  ELBOX_BOARD_WRGN42
#undef  ELBOX_BOARD_WRGND08
#undef  ELBOX_BOARD_WRGND09
#undef  ELBOX_BOARD_WRGND10
#undef  ELBOX_BOARD_IP8KEVAL
#undef  ELBOX_BOARD_WRGND11
#undef  ELBOX_BOARD_WRGND14
#undef  ELBOX_BOARD_WRGND18
#undef  ELBOX_BOARD_WRGNS01
#undef  ELBOX_BOARD_WTDRG01
#undef  ELBOX_BOARD_WTDRV01
#undef  ELBOX_BOARD_WHDRV01
#undef  ELBOX_BOARD_WRGN33
#undef  ELBOX_BOARD_HPW310AV
#undef  ELBOX_BOARD_HPW310AV_ATHEROS
#undef  ELBOX_BOARD_WRGAC01
#undef  ELBOX_BOARD_WRGAC02
#undef  ELBOX_BOARD_WRGAC02e
#undef  ELBOX_BOARD_WRGAC02_2WAN
#undef  ELBOX_BOARD_WRGAC03
#undef  ELBOX_BOARD_WRGAC05
#undef  ELBOX_BOARD_WRGAC08
#undef  ELBOX_BOARD_WRGAC09
#undef  ELBOX_BOARD_WRGAC11
#undef  ELBOX_BOARD_WRGAC13
#undef  ELBOX_BOARD_WRGAC14
#undef  ELBOX_BOARD_WRGAC23
#undef  ELBOX_BOARD_WRGAC16
#define ELBOX_BOARD_WRGAC25 1
#undef  ELBOX_BOARD_WRGOTT01
#undef  ELBOX_BOARD_WRGAC29
#undef  ELBOX_BOARD_WRGAC33
#undef  ELBOX_BOARD_WRGAC33A
#undef  ELBOX_BOARD_WRGAC34
#undef  ELBOX_BOARD_WRGAC37
#define ELBOX_BOARD_NAME "wrgac25"
#define ELBOX_BSP_RTLSDK_3_2 1
#define ELBOX_BSP_RTLSDK_3_2_TARGET "rtl819xD"
#define ELBOX_BSP_NAME "rtlsdk32-linux-2.6.30"
#define ELBOX_LINUX_MAJOR 2
#define ELBOX_LINUX_MINOR 6
#define ELBOX_LINUX_BUILD 30
#define ELBOX_INSTALL_LIBGCC_A_SO 1
#define ELBOX_INSTALL_LIBRT_SO 1
#define ELBOX_INSTALL_LIBPTHREAD_SO 1
#undef  ELBOX_INSTALL_LIBGCC_S_4181_SO

/* Realtek tool set */
#undef  ELBOX_INSTALL_REALTEK_APMIB
#undef  ELBOX_INSTALL_REALTEK_IAPP
#undef  ELBOX_INSTALL_REALTEK_IGMPPROXY
#undef  ELBOX_INSTALL_REALTEK_IWCONTROL
#undef  ELBOX_INSTALL_REALTEK_UDPSERVER
#undef  ELBOX_INSTALL_REALTEK_SYSCONF
#undef  ELBOX_INSTALL_REALTEK_FLASH
#undef  ELBOX_INSTALL_REALTEK_IOCTL
#undef  ELBOX_TEMPLATE_GW_WIFI
#undef  ELBOX_TEMPLATE_GW_WIFI_2WAN
#undef  ELBOX_TEMPLATE_AP_WIFI
#undef  ELBOX_TEMPLATE_AP_WIFI_CMCC
#undef  ELBOX_TEMPLATE_AP_GW_WIFI
#undef  ELBOX_TEMPLATE_AP_GAMING
#undef  ELBOX_TEMPLATE_AP_WIFI_CLOUD
#undef  ELBOX_TEMPLATE_AP_WIFI_WAN
#undef  ELBOX_TEMPLATE_TENDER
#undef  ELBOX_TEMPLATE_EMPTY
#define ELBOX_TEMPLATE_ARIES 1
#undef  ELBOX_TEMPLATE_ARIES_BRIDGE_AP
#undef  ELBOX_TEMPLATE_TAURUS
#undef  ELBOX_TEMPLATE_ECOS
#define ELBOX_PROJECT_SEATTLE 1
#define ELBOX_TEMPLATE_NAME "aries"
#define ELBOX_BRAND_NAME "dlink.2013gui"
#define ELBOX_MODEL_NAME "dir850l"

/* Aries Configuration */

/* HTTP/CGI kits */
#define ELBOX_ARIES_SESSION_BASE "/runtime/session"

/* Features */
#define ELBOX_ARIES_FEATURE_ROUTER_GATEWAY 1
#undef  ELBOX_ARIES_FEATURE_BRIDGE_AP
#define ELBOX_ARIES_USE_DANIELS_CONE_NAT 1
#define ELBOX_ARIES_USE_UDEV 1
#undef  ELBOX_ARIES_USE_UDEV_USB3G_SUPPORT
#define ELBOX_ARIES_USE_UDEV_USB_STORAGE_SUPPORT 1
#undef  ELBOX_ARIES_USE_BACKUP_CONNECTION
#undef  ELBOX_TEMPLATE_ARIES_NET_SNMP_5_5
#undef  ELBOX_TEMPLATE_ARIES_PHPCONTROL
#undef  ELBOX_TEMPLATE_ARIES_ADVANCED_LAYOUT
#define ELBOX_TEMPLATE_ARIES_NEW_WIFI_UID 1
#undef  ELBOX_TEMPLATE_ARIES_UNIFIED_DNS
#define ELBOX_TEMPLATE_ARIES_STORAGE_SUPPORT 1
#define ELBOX_TEMPLATE_ARIES_ENABLE_USER_MANAGEMENT 1
#define ELBOX_TEMPLATE_ARIES_MYDLINK_SUPPORT 1
#define ELBOX_PROGS_PRIV_MYDLINK_DIR "DIR-850LB1"
#define ELBOX_PROGS_PRIV_MYDLINK_MTDBLOCK "/dev/mtdblock/9"
#define ELBOX_PROGS_PRIV_MYDLINK_OPENSSL 1
#undef  ELBOX_PROGS_PRIV_MYDLINK_CYASSL
#undef  ELBOX_BRAND_ARIES_ALPHA
#undef  ELBOX_BRAND_ARIES_ALPHAAC
#undef  ELBOX_BRAND_ARIES_BRAVO
#undef  ELBOX_BRAND_ARIES_DLOB
#undef  ELBOX_BRAND_ARIES_DLOB_HANS
#undef  ELBOX_BRAND_ARIES_DKBS
#undef  ELBOX_BRAND_ARIES_IOWBR
#undef  ELBOX_BRAND_ARIES_IOWAP
#undef  ELBOX_BRAND_ARIES_TFNET
#undef  ELBOX_BRAND_ARIES_HAIER
#undef  ELBOX_BRAND_ARIES_BFLWHR
#undef  ELBOX_BRAND_ARIES_KEEBOX
#undef  ELBOX_BRAND_ARIES_PCI
#undef  ELBOX_BRAND_ARIES_BESTBUY
#undef  ELBOX_BRAND_ARIES_SAMSUNG
#undef  ELBOX_BRAND_ARIES_ETS
#undef  ELBOX_BRAND_ARIES_TRENDNET
#undef  ELBOX_BRAND_ARIES_SONY
#undef  ELBOX_BRAND_ARIES_NONBRAND
#define ELBOX_BRAND_ARIES_DLINK_2013GUI 1
#undef  ELBOX_BRAND_ARIES_PANASONIC
#undef  ELBOX_BRAND_ARIES_NECAT
#undef  ELBOX_MODEL_ARIES_DLINK_2013GUI_DIR845
#undef  ELBOX_MODEL_ARIES_DLINK_2013GUI_DIR518
#undef  ELBOX_MODEL_ARIES_DLINK_2013GUI_DIR816L
#undef  ELBOX_MODEL_ARIES_DLINK_2013GUI_DIR818L
#undef  ELBOX_MODEL_ARIES_DLINK_2013GUI_DAP1320B
#undef  ELBOX_MODEL_ARIES_DLINK_2013GUI_DIR880
#undef  ELBOX_MODEL_ARIES_DLINK_2013GUI_DIR868
#define ELBOX_MODEL_ARIES_DLINK_2013GUI_DIR850L 1
#undef  ELBOX_MODEL_ARIES_DLINK_2013GUI_DIR850LCTL
#undef  ELBOX_MODEL_ARIES_DLINK_2013GUI_DIR850LONEPAGE
#undef  ELBOX_MODEL_ARIES_DLINK_2013GUI_DIR850LIN
#undef  ELBOX_MODEL_ARIES_DLINK_2013GUI_DIR882L
#undef  ELBOX_MODEL_ARIES_DLINK_2013GUI_DIR883L
#undef  ELBOX_MODEL_ARIES_DLINK_2013GUI_DIR860LB
#undef  ELBOX_MODEL_ARIES_DLINK_2013GUI_DIR859

/* config interface name */

/* Features configuration */
#undef  LOGNUM
#define ELBOX_USE_IPV6 1

/* --- */
#undef  ELBOX_USB
#define ELBOX_NETWORK 1
#undef  ELBOX_NETWORK_ROUTER_GATEWAY
#undef  ELBOX_NETWORK_BRIDGE_AP
#define ELBOX_NETWORK_PHYINF_PROFILES "2"
#define ELBOX_NETWORK_WAN_PROFILES "1"
#define ELBOX_NETWORK_LAN_PROFILES "4"
#undef  ELBOX_NETWORK_WIFI
#define ELBOX_NETWORK_IPV6 1
#undef  ELBOX_NETWORK_3G
#undef  ELBOX_NETWORK_WAN_DETECT
#undef  ELBOX_NETWORK_UPNP
#undef  ELBOX_NETWORK_DANIELS_CONE_NAT
#undef  ELBOX_NETWORK_BACKUP_CONNECTION
#undef  ELBOX_NETWORK_PHPCONTROL
#undef  ELBOX_NETWORK_ADVANCED_LAYOUT
#undef  ELBOX_NETWORK_UNIFIED_DNS

/* HTTP/CGI kits */
#define ELBOX_NETWORK_SESSION_BASE "/runtime/session"
#undef  ELBOX_STORAGE
#undef  ELBOX_USER_MANAGEMENT
#undef  ELBOX_CONNECTED_HOME

/* Language Configuration */

/* Language options */
#undef  ELBOX_CREATE_LANGUAGE_PACK

/* Languages */
#undef  ELBOX_LANGUAGE_EN
#undef  ELBOX_LANGUAGE_JA
#undef  ELBOX_LANGUAGE_DE
#undef  ELBOX_LANGUAGE_ZH_TW
#undef  ELBOX_LANGUAGE_ZH_CN
#undef  ELBOX_LANGUAGE_FR
#undef  ELBOX_LANGUAGE_ES
#undef  ELBOX_LANGUAGE_IT
#undef  ELBOX_LANGUAGE_NL
#undef  ELBOX_LANGUAGE_PT
#undef  ELBOX_LANGUAGE_FI
#undef  ELBOX_LANGUAGE_SV
#undef  ELBOX_LANGUAGE_NO
#undef  ELBOX_LANGUAGE_DA
#undef  ELBOX_LANGUAGE_KO
#undef  ELBOX_LANGUAGE_PL
#undef  ELBOX_LANGUAGE_RU
#undef  ELBOX_LANGUAGE_HE
#undef  ELBOX_LANGUAGE_HU
#undef  ELBOX_LANGUAGE_EL
#undef  ELBOX_LANGUAGE_TR
#undef  ELBOX_LANGUAGE_CS
#undef  ELBOX_LANGUAGE_TH
#undef  ELBOX_LANGUAGE_AR
#undef  ELBOX_LANGUAGE_IS

/* Default Language */
#define ELBOX_DEFAULT_LANGUAGE_NONE 1
#undef  ELBOX_DEFAULT_LANGUAGE_EN
#undef  ELBOX_DEFAULT_LANGUAGE_JA
#undef  ELBOX_DEFAULT_LANGUAGE_DE
#undef  ELBOX_DEFAULT_LANGUAGE_ZH_TW
#undef  ELBOX_DEFAULT_LANGUAGE_ZH_CN
#undef  ELBOX_DEFAULT_LANGUAGE_FR
#undef  ELBOX_DEFAULT_LANGUAGE_ES
#undef  ELBOX_DEFAULT_LANGUAGE_IT
#undef  ELBOX_DEFAULT_LANGUAGE_NL
#undef  ELBOX_DEFAULT_LANGUAGE_PT
#undef  ELBOX_DEFAULT_LANGUAGE_FI
#undef  ELBOX_DEFAULT_LANGUAGE_SV
#undef  ELBOX_DEFAULT_LANGUAGE_NO
#undef  ELBOX_DEFAULT_LANGUAGE_DA
#undef  ELBOX_DEFAULT_LANGUAGE_KO
#undef  ELBOX_DEFAULT_LANGUAGE_PL
#undef  ELBOX_DEFAULT_LANGUAGE_RU
#undef  ELBOX_DEFAULT_LANGUAGE_HE
#undef  ELBOX_DEFAULT_LANGUAGE_HU
#undef  ELBOX_DEFAULT_LANGUAGE_EL
#undef  ELBOX_DEFAULT_LANGUAGE_TR
#undef  ELBOX_DEFAULT_LANGUAGE_CS
#undef  ELBOX_DEFAULT_LANGUAGE_TH
#undef  ELBOX_DEFAULT_LANGUAGE_AR
#undef  ELBOX_DEFAULT_LANGUAGE_IS

/* Programs Configuration */

/* GPL Programs */

/* ------------------------ Busybox ------------------------ --- */
#define ELBOX_BUSYBOX 1
#undef  ELBOX_PROGS_GPL_BUSYBOX_1_00
#undef  ELBOX_PROGS_GPL_BUSYBOX_1_11_1
#define ELBOX_PROGS_GPL_BUSYBOX_1_14_1 1
#undef  ELBOX_PROGS_GPL_BUSYBOX_1_18_1
#undef  ELBOX_PROGS_GPL_BUSYBOX_1_22_1
#undef  ELBOX_PROGS_GPL_ASSIGN_DEV_RUN_SHELL_ON
#undef  ELBOX_PROGS_GPL_BUSYBOX_1_14_1_NOIP
#undef  ELBOX_PROGS_GPL_BUSYBOX_NOBZIP2
#undef  ELBOX_PROGS_GPL_BUSYBOX_NO_2_4_MODULES
#undef  ELBOX_PROGS_GPL_TFTP_FTP_GET_PUT_FW_CONFIG
#undef  ELBOX_BUSYBOX_DYNAMIC_LINKING
#undef  ELBOX_BUSYBOX_HAVE_MDEV
#undef  ELBOX_BUSYBOX_USE_FANCY_PING
#undef  ELBOX_BUSYBOX_HAVE_EXPR

/* ------------------------ Programs ----------------------- --- */
#undef  ELBOX_ARP_SPOOF
#undef  ELBOX_PROGS_GPL_BPALOGIN
#undef  ELBOX_PROGS_GPL_CHILLISPOT
#undef  ELBOX_PROGS_GPL_CTORRENT
#undef  ELBOX_PROGS_GPL_DIBBLER
#undef  ELBOX_PROGS_GPL_DHCPV6_LINUX
#define ELBOX_USE_DNS 1
#undef  ELBOX_PROGS_GPL_DNRD_2_10
#undef  ELBOX_PROGS_GPL_DNSMASQ
#undef  ELBOX_PROGS_GPL_DNSMASQ_2_76
#define ELBOX_PROGS_GPL_DNSMASQ_2_78 1

/*    Dnsmasq configuration */
#define ELBOX_PROGS_GPL_DNSMASQ_HAVE_BROKEN_RTC 1
#define ELBOX_PROGS_GPL_DNSMASQ_NO_TFTP 1
#define ELBOX_PROGS_GPL_DNSMASQ_NOUSER_ALPHA 1
#define ELBOX_PROGS_GPL_DNSMASQ_NOPRCTL_ALPHA 1
#define ELBOX_PROGS_GPL_DNSMASQ_HELPER_SUPPORT_ALPHA 1
#define ELBOX_PROGS_GPL_DNSMASQ_ADVANCE_DNS_SERVICE_ALPHA 1
#undef  ELBOX_PROGS_GPL_NETSNIPER
#undef  ELBOX_PROGS_GPL_DNSMASQ_INOTIFY_ALPHA
#define ELBOX_PROGS_GPL_E2FSPROGS 1
#define ELBOX_PROGS_GPL_E2FSPROGS_1_41_12 1
#undef  ELBOX_PROGS_GPL_ECOS_PPPD
#undef  ELBOX_PROGS_GPL_ECOS_UDHCP
#undef  ELBOX_PROGS_GPL_ECOS_DHCPC
#undef  ELBOX_PROGS_GPL_ECOS_DHCPD
#undef  ELBOX_HOSTAPD
#define ELBOX_HTTPD 1
#undef  ELBOX_PROGS_GPL_MATHOPD
#undef  ELBOX_PROGS_GPL_MATHOPD_STANDARD
#define ELBOX_PROGS_GPL_MATHOPD_16 1
#undef  ELBOX_PROGS_GPL_ATHTTPD

/* Upload externel file */
#undef  ELBOX_PROGS_GPL_MATHOPD_EXTERNAL_FILE
#undef  ELBOX_PROGS_GPL_MATHOPD_ACL_IMPORT
#undef  ELBOX_PROGS_GPL_MATHOPD_EXTERNAL_BT_FILE
#undef  ELBOX_PROGS_GPL_MATHOPD_DUAL_RUNTIME_IMAGE
#undef  ELBOX_PROGS_GPL_IGMPPROXY
#undef  ELBOX_PROGS_GPL_IPPERSONALITY
#undef  ELBOX_PROGS_GPL_IPROUTE2_2_6_8
#define ELBOX_PROGS_GPL_IPROUTE2_2_6_33 1
#undef  ELBOX_PROGS_GPL_IPROUTE2_3_12_0
#undef  ELBOX_PROGS_GPL_TC_FOR_AP
#undef  ELBOX_PROGS_GPL_TC_U32_IP_PORT_RANGE
#define ELBOX_IPTABLES 1
#undef  ELBOX_PROGS_GPL_IPTABLES_1_2_6A
#undef  ELBOX_PROGS_GPL_IPTABLES_1_2_7A
#undef  ELBOX_PROGS_GPL_IPTABLES_1_2_9
#undef  ELBOX_PROGS_GPL_IPTABLES_1_3_5
#define ELBOX_PROGS_GPL_IPTABLES_1_4_7 1
#undef  ELBOX_PROGS_GPL_IPTABLES_1_4_10
#undef  ELBOX_PROGS_GPL_IPTABLES_1_4_21
#define ELBOX_IPTABLES_L7_EXT 1
#define ELBOX_IPTABLES_RTL_DST_MAC_SUPPORT 1
#define ELBOX_PROGS_GPL_ITUNES_SERVER 1
#define ELBOX_MDNSRESPONDER 1
#define ELBOX_PROGS_GPL_MDNSRESPONDER_320_5_1 1
#undef  ELBOX_PROGS_GPL_MDNSRESPONDER_544
#undef  ELBOX_KLOGD
#undef  ELBOX_PROGS_GPL_LPRNG_3_8_27
#define ELBOX_MINIDLNA 1
#undef  ELBOX_PROGS_GPL_MINIDLNA_1019
#define ELBOX_PROGS_GPL_MINIDLNA_1024 1
#define ELBOX_PROGS_GPL_NSBBOX 1

/* NotSoBusyBOX configuration */
#undef  CONFIG_NSBBOX_BASE64
#define CONFIG_NSBBOX_BRCTL 1
#define CONFIG_NSBBOX_BRCTL_BWCTRL 1
#undef  CONFIG_NSBBOX_BRCTL_IOAPNL
#define CONFIG_NSBBOX_BRCTL_PORTFORWARD 1
#undef  CONFIG_NSBBOX_BRCTL_PORTDENYLIST
#undef  CONFIG_NSBBOX_BRCTL_IGMP
#undef  CONFIG_NSBBOX_BRCTL_AP_OPERATION_MODE
#undef  CONFIG_NSBBOX_BRCTL_APC_OPERATION_MODE
#undef  CONFIG_NSBBOX_BRCTL_DHCP_SERVER_ENABLE
#undef  CONFIG_NSBBOX_BRCTL_E_PARTITION
#undef  CONFIG_NSBBOX_BRCTL_MDNSFILTER
#undef  CONFIG_NSBBOX_BRCTL_W_PARTITION
#undef  CONFIG_NSBBOX_BRCTL_ETHLINK
#undef  CONFIG_NSBBOX_BRCTL_LIMITED_ADMIN
#undef  CONFIG_NSBBOX_BRCTL_PING_CONTROL
#undef  CONFIG_NSBBOX_BRCTL_MULTI_VLAN
#undef  CONFIG_NSBBOX_BRCTL_MAT_STATUS
#undef  CONFIG_NSBBOX_BRCTL_MAC_CLONE
#define CONFIG_NSBBOX_NTPCLIENT 1
#define CONFIG_NSBBOX_SMTPCLIENT 1
#define CONFIG_NSBBOX_VCONFIG 1
#undef  CONFIG_NSBBOX_BRCTL_FORWARDING_DB
#define ELBOX_PPPD 1
#define ELBOX_PROGS_GPL_PPPD_ALPHA 1

/* Accelerate pptp */
#define ELBOX_PROGS_GPL_PPPD_ACCEL_PPTP 1
#define ELBOX_PROGS_GPL_PPPD_ACCEL_PPTP_PLUS 1

/* IPv6 tunnel support l2tp */
#undef  ELBOX_PROGS_GPL_PPPD_IPV6_L2TP
#undef  ELBOX_PROGS_GPL_PURE_FTPD
#undef  ELBOX_PROGS_GPL_QUAGGA
#undef  ELBOX_PROGS_GPL_QUOTA
#undef  ELBOX_PROGS_GPL_RADVD
#define ELBOX_PROGS_GPL_RADVD_NOUSER_ALPHA 1
#define ELBOX_PROGS_GPL_RADVD_NOLIBFL 1
#undef  ELBOX_PROGS_GPL_RADVD_1_7
#define ELBOX_PROGS_GPL_RADVD_1_8 1

/* Linux IPv6 Router Advertisement Daemon (radvd) configuration */
#undef  ELBOX_PROGS_GPL_NTFS_3G
#define ELBOX_SAMBA 1
#undef  ELBOX_PROGS_GPL_SAMBA_3_0_7
#undef  ELBOX_PROGS_GPL_SAMBA_3_0_25a
#define ELBOX_PROGS_GPL_SAMBA_3_0_24 1
#undef  ELBOX_PROGS_GPL_SAMBA_3_0_24_LITE
#define ELBOX_PROGS_GPL_SFDISK 1
#define ELBOX_PROGS_GPL_SFDISK_2_18 1
#undef  ELBOX_PROGS_GPL_NET_SNMP
#undef  ELBOX_AP_WLAN_TELECOM_STATISTIC
#undef  ELBOX_PROGS_GPL_STUNNEL
#undef  ELBOX_PROGS_GPL_STUPID_FTPD
#undef  ELBOX_USE_SYSLOG
#undef  ELBOX_PROGS_GPL_TELNETD
#undef  ELBOX_PROGS_GPL_TINYLOGIN
#undef  ELBOX_TSPC
#undef  ELBOX_PROGS_GPL_TZCOMPILER
#define ELBOX_PROGS_GPL_UDEV 1
#define ELBOX_UDHCP 1

/* Use Unicasting and broadcasting request */
#define ELBOX_PROGS_GPL_UDHCP_REQUEST_BROADCAST 1
#undef  ELBOX_PROGS_GPL_UDHCP_0_9_8
#define ELBOX_PROGS_GPL_UDHCPCD 1
#undef  ELBOX_PROGS_GPL_UDHCP_SUPER_DMZ
#undef  ELBOX_PROGS_GPL_UDHCP_HOLD_LAN_IP
#undef  ELBOX_PROGS_GPL_UPNPIGD
#undef  ELBOX_PROGS_GPL_USB_MODE_SWITCH
#undef  ELBOX_PROGS_GPL_WOL
#define ELBOX_PROGS_GPL_WIDE_DHCPV6 1
#undef  ELBOX_PROGS_GPL_WIRELESS_TOOLS
#undef  ELBOX_PROGS_GPL_WIRELESS_TOOLS_ATHEROS_29
#define ELBOX_PROGS_GPL_WIRELESS_TOOLS_REALTEK_29 1
#undef  ELBOX_PROGS_GPL_XSUPPLICANT
#undef  ELBOX_PROGS_GPL_ZEBRA
#undef  ELBOX_RADIUSCLIENT
#undef  ELBOX_OPENLDAP
#undef  ELBOX_PROGS_GPL_LLDPD_0_7_7_ALPHA
#define ELBOX_PROGS_GPL_ECMH 1
#define ELBOX_PROGS_GPL_IPUTILS 1

/* iputils configuration */
#undef  ELBOX_PROGS_GPL_IPUTILS_TRACEPATH
#undef  ELBOX_PROGS_GPL_IPUTILS_PING
#undef  ELBOX_PROGS_GPL_IPUTILS_CLOCKDIFF
#undef  ELBOX_PROGS_GPL_IPUTILS_RDISC
#undef  ELBOX_PROGS_GPL_IPUTILS_ARPING
#undef  ELBOX_PROGS_GPL_IPUTILS_TFTPD
#undef  ELBOX_PROGS_GPL_IPUTILS_TRACEPATH6
#undef  ELBOX_PROGS_GPL_IPUTILS_TRACEROUTE6
#define ELBOX_PROGS_GPL_IPUTILS_PING6 1
#define ELBOX_PROGS_GPL_NDISC6_0_9_9 1
#define ELBOX_PROGS_GPL_UPNPC 1

/* Support IGD forwarding function */
#undef  ELBOX_PROGS_GPL_UPNPC_IGD_FORWARDER
#undef  ELBOX_PROGS_GPL_BDB
#define ELBOX_PROGS_GPL_IMAGE_TOOLS 1
#undef  ELBOX_PROGS_GPL_ZIP
#undef  ELBOX_PROGS_GPL_IPERF
#undef  ELBOX_PROGS_GPL_PPTPD
#undef  ELBOX_TRANSMISSION
#undef  ELBOX_PROGS_GPL_SHAIRPORT
#undef  ELBOX_PROGS_GPL_MPG123
#undef  ELBOX_PROGS_GPL_PLATINUM
#undef  ELBOX_PROGS_GPL_I2C_TOOLS
#undef  ELBOX_PROGS_GPL_MTDUTILS

/* ------------------------ Libraries ------------------------ --- */
#undef  ELBOX_FLEX
#undef  ELBOX_LIBNL
#define ELBOX_PROGS_GPL_LIB_GSASL 1
#define ELBOX_PROGS_GPL_LIB_GSASL_0_2_6 1
#define ELBOX_OPENSSL 1
#undef  ELBOX_PROGS_GPL_OPENSSL_USE_STATIC_LINK
#undef  ELBOX_PROGS_GPL_OPENSSL_098A
#undef  ELBOX_PROGS_GPL_OPENSSL_098E
#undef  ELBOX_PROGS_GPL_OPENSSL_098E_GCC_4_2
#undef  ELBOX_PROGS_GPL_OPENSSL_098G
#undef  ELBOX_PROGS_GPL_OPENSSL_098ZA
#undef  ELBOX_PROGS_GPL_OPENSSL_098ZC
#undef  ELBOX_PROGS_GPL_OPENSSL_102D
#define ELBOX_PROGS_GPL_OPENSSL_102H 1
#undef  ELBOX_PROGS_GPL_LIBTORRENT
#undef  ELBOX_ZLIB
#define ELBOX_PROGS_GPL_EMAILCLIENT 1
#undef  ELBOX_PROGS_GPL_EBTABLES
#undef  ELBOX_PROGS_GPL_EBTABLES_2_0_10
#undef  ELBOX_PROGS_GPL_CLOUD_MANAGE_UPDATEFW
#define ELBOX_PROGS_GPL_LIBICONV_1_9_1 1
#define ELBOX_SQLITE 1
#define ELBOX_PROGS_GPL_SQLITE_374 1
#undef  ELBOX_CURL
#undef  ELBOX_LIBEVENT
#undef  ELBOX_PROGS_GPL_OPENZWAVE

/* Private Programs (developed by AlphaNetworks) */
#undef  ELBOX_PROGS_PRIV_CALLMGR
#define ELBOX_XMLDB 1
#undef  ELBOX_PROGS_PRIV_XMLDB
#define ELBOX_PROGS_PRIV_XMLDB3 1

/* New features support */
#define ELBOX_XMLDB_SAVE_ATTRIBUTE 1
#define ELBOX_PROGS_PRIV_RGBIN 1

/* RGBIN configuration */

/* GPL tools - DO NOT use the GPL code here, use PROG.GPL/NSBBOX instead !! */
#undef  CONFIG_RGBIN_BASE64
#undef  CONFIG_RGBIN_BRCTL
#undef  CONFIG_RGBIN_PING_CONTROL_USE_PROC_FILE
#undef  CONFIG_RGBIN_NTPCLIENT
#undef  CONFIG_RGBIN_SMTPCLIENT
#undef  CONFIG_RGBIN_VCONFIG
#undef  CONFIG_RGBIN_BRCTL_WEB_REDIRECT

/* Private tools - ONLY use the private code here !! */
#define CONFIG_RGBIN_SEAMA 1
#define CONFIG_RGBIN_HTTPC 1
#define CONFIG_RGBIN_GENUUID 1
#define CONFIG_RGBIN_PFILE 1
#define CONFIG_RGBIN_SCUT 1
#define CONFIG_RGBIN_TLOGS 1
#undef  CONFIG_RGBIN_ASESSION
#undef  CONFIG_RGBIN_MPCONVERT
#undef  CONFIG_RGBIN_DAYCONVERT
#undef  CONFIG_RGBIN_CHNET
#undef  CONFIG_RGBIN_ROUTETABLE
#undef  CONFIG_RGBIN_PARSEINFO
#define CONFIG_RGBIN_LOGIN 1
#define CONFIG_RGBIN_ARPPING 1
#define CONFIG_RGBIN_GETHOSTIP 1
#define CONFIG_RGBIN_GETBOOTVER 1
#define CONFIG_RGBIN_GETBOOTVER_STRING 1
#undef  CONFIG_RGBIN_COREDE
#define CONFIG_RGBIN_USOCKC 1
#define CONFIG_RGBIN_SUSOCKC 1
#undef  CONFIG_RGBIN_RSTRCMP
#undef  CONFIG_RGBIN_GETSYS
#undef  CONFIG_RGBIN_USB3G_KIT
#undef  CONFIG_RGBIN_REMSERIAL
#undef  CONFIG_RGBIN_USBRESET
#undef  CONFIG_RGBIN_CHECK_CONNECTION
#undef  CONFIG_RGBIN_ARPMONITOR
#undef  CONFIG_RGBIN_3GCHAT
#undef  CONFIG_RGBIN_SIMUNLOCK
#define CONFIG_RGBIN_IPV6IP 1
#define CONFIG_RGBIN_IPV6PDIP 1
#undef  CONFIG_RGBIN_EUI64
#undef  CONFIG_RGBIN_SENDTRAP
#define CONFIG_RGBIN_SYSLOGMSG 1
#undef  CONFIG_RGBIN_MEMTEST
#undef  CONFIG_RGBIN_FLASHTEST
#undef  CONFIG_RGBIN_DNSQUERY
#undef  CONFIG_RGBIN_FWINFO
#undef  CONFIG_RGBIN_USRCRYPT
#undef  CONFIG_RGBIN_HMAC

/* DevData - Permanent Data */
#define CONFIG_RGBIN_DEVDATA 1
#define CONFIG_RGBIN_DEVDATA_MTDBLOCK "/dev/mtdblock/4"
#define CONFIG_RGBIN_DEVDATA_OFFSET 0x0
#define CONFIG_RGBIN_DEVDATA_SIZE 0x10000

/* DevConf - User Configuration */
#define CONFIG_RGBIN_DEVCONF 1
#define CONFIG_RGBIN_DEVCONF_MTDBLOCK "/dev/mtdblock/3"
#define CONFIG_RGBIN_DEVCONF_OFFSET 0x0
#define CONFIG_RGBIN_DEVCONF_SIZE 0xd800
#define CONFIG_RGBIN_DEVCONF_SSL_OFFSET 0xd800
#define CONFIG_RGBIN_DEVCONF_SSL_SIZE 0x2800
#undef  CONFIG_RGBIN_RW_CHAR_MTD

/* outdated utilities */
#undef  ELBOX_RGBIN_RGCFG
#undef  CONFIG_RGBIN_RGDB
#define CONFIG_RGBIN_TCPREQUEST 1
#undef  CONFIG_RGBIN_SCHEDULE_FOR_NTP_CONNECT_COUNTER
#undef  CONFIG_RGBIN_LOGIN_HIDE_PASSWORD
#undef  ELBOX_ALPHA_XGI
#undef  ELBOX_IPSEC_PT
#undef  ELBOX_IFRESETCNT
#undef  ELBOX_STUN_NAT
#define ELBOX_TURBONAT 1
#undef  ELBOX_PROGS_PRIV_TURBONAT
#define ELBOX_PROGS_PRIV_TURBONAT_26 1
#define ELBOX_PROGS_PRIV_TURBONAT_QOS 1
#define ELBOX_PROGS_PRIV_TURBONAT_UBCOM 1
#undef  ELBOX_PROGS_PRIV_TURBONAT_TCMARK
#undef  ELBOX_PROGS_PRIV_TURBONAT_CONNMARK
#define ELBOX_PROGS_PRIV_BWC 1
#undef  ELBOX_PROGS_PRIV_FLOWMETER
#undef  ELBOX_PROGS_PRIV_APX
#define ELBOX_LOG_MESSAGE 1
#define ELBOX_PROGS_PRIV_LOG_ENGLISH 1
#undef  ELBOX_MADWIFI
#undef  ELBOX_PROGS_PRIV_MADWIFI_PANASONIC_tzcmp01
#undef  ELBOX_PROGS_PRIV_ART_AP83
#undef  ELBOX_PROGS_PRIV_ART_AP101
#undef  ELBOX_PROGS_PRIV_ART_PB44
#undef  ELBOX_PROGS_PRIV_ART_DB12X
#undef  ELBOX_PROGS_PRIV_ART_AP135
#undef  ELBOX_PROGS_PRIV_ART_AP123_AR93
#undef  ELBOX_PROGS_PRIV_MADWIFI_AP83
#undef  ELBOX_PROGS_PRIV_MADWIFI_CAVIUM
#undef  ELBOX_PROGS_PRIV_MADWIFI_FUSION_CAVIUM
#undef  ELBOX_PROGS_PRIV_MADWIFI_FUSION_CAVIUM_SEATTLE
#undef  ELBOX_PROGS_PRIV_MADWIFI_LSDK_WLAN_V9
#undef  ELBOX_PROGS_PRIV_MADWIFI_LSDK_WLAN_V10
#undef  ELBOX_PROGS_PRIV_MADWIFI_LSDK_WLAN_AP135
#undef  ELBOX_PROGS_PRIV_QCA_WIFI_DB149
#undef  ELBOX_RALINK_WIFI
#undef  ELBOX_PROGS_PRIV_RALINK_INIC
#undef  ELBOX_RT2860V2
#undef  ELBOX_RT2561
#undef  ELBOX_BROADCOM_WIFI
#undef  ELBOX_PROGS_PRIV_RALINK_DRIVER
#undef  ELBOX_PROGS_PRIV_RALINK_APP
#undef  ELBOX_PROGS_PRIV_RALINK_RT3090
#undef  ELBOX_PROGS_PRIV_RALINK_RT3883_3662
#undef  ELBOX_SAMSUNG_EZLINK
#undef  ELBOX_PROGS_PRIV_UPNPKITS
#undef  ELBOX_PROGS_PRIV_NEAPS
#undef  ELBOX_PROGS_PRIV_NEAPS_ARIES
#undef  ELBOX_PROGS_PRIV_AP_NEAP
#undef  ELBOX_PROGS_PRIV_AP_NEAP_V2
#undef  ELBOX_PROGS_PRIV_MANAGED_AP
#undef  ELBOX_PROGS_PRIV_IGMP
#undef  ELBOX_PROGS_PRIV_IGMPPROXY
#define ELBOX_PROGS_PRIV_MRD 1
#undef  ELBOX_PROGS_PRIV_SCHEDULED
#undef  ELBOX_PROGS_PRIV_COMMON_SCRIPTS
#undef  ELBOX_PROGS_PRIV_DHCPXMLPATCH
#define ELBOX_PROGS_PRIV_UPDATELEASES 1
#undef  ELBOX_PROGS_PRIV_MTDTEST
#define ELBOX_PROGS_PRIV_PORTT 1
#undef  ELBOX_PROGS_PRIV_NETSTAR
#undef  ELBOX_PROGS_PRIV_RESOLVED
#undef  ELBOX_PROGS_PRIV_PROXYD
#undef  ELBOX_PROGS_PRIV_MIIICASA
#undef  ELBOX_PROGS_PRIV_KDBG_AGENT
#define ELBOX_DDNS 1

/* Select DDNS updater implementation */
#define ELBOX_PROGS_PRIV_DYNDNS 1
#define ELBOX_PROGS_PRIV_PEANUT 1
#undef  ELBOX_PROGS_PRIV_BDTOOL
#undef  ELBOX_PROGS_PRIV_BDCFG
#define ELBOX_PROGS_PRIV_LLD2D 1
#undef  ELBOX_PROGS_PRIV_CMCGI
#undef  ELBOX_PROGS_PRIV_ART
#undef  ELBOX_PROGS_PRIV_YAHOO_WIDGET
#undef  ELBOX_PROGS_PRIV_TRAFFICCTRL
#undef  ELBOX_PROGS_PRIV_ALPHA_HOTPLUG
#undef  ELBOX_PROGS_PRIV_WCN_UFD
#undef  ELBOX_PROGS_PRIV_MADWIFI_DUALBAND
#undef  ELBOX_PROGS_PRIV_ALPHA_NLS_DRV
#undef  ELBOX_PROGS_PRIV_WPSTOOLS
#undef  ELBOX_PROGS_PRIV_WPS2TOOLS
#undef  ELBOX_PROGS_PRIV_WPA_SUPPLICANT
#undef  ELBOX_PROGS_PRIV_WPA_SUPPLICANT_0_5
#undef  ELBOX_PROGS_PRIV_CAPWAP
#undef  ELBOX_PROGS_PRIV_CLI
#undef  ELBOX_FIRMWARE_HEADER_VERSION_CONTROL
#undef  ELBOX_PROGS_PRIV_CLI_SEATTLE
#undef  ELBOX_WLXMLPATCHV2
#undef  ELBOX_PROGS_PRIV_CLIENTINFO_TXRX_BYTES_COUNTER
#undef  ELBOX_PROGS_PRIV_NETBIOS
#undef  ELBOX_PROGS_PRIV_ETHLINK
#define ELBOX_PROGS_PRIV_SENDMAIL 1
#undef  ELBOX_PROGS_PRIV_STATIC_DHCP
#define ELBOX_PROGS_PRIV_SERVD 1
#define ELBOX_PROGS_PRIV_CGIBIN_ARIES 1

/* CGI bin of Aries */

/* CGI Programs */
#define CONFIG_CGIBIN_ARIES_AUTH_USERNAME_CASELESS 1
#define CONFIG_CGIBIN_ARIES_PHPCGI 1
#define CONFIG_CGIBIN_ARIES_PHPCGI_MAXFILESIZE 0x80000
#define CONFIG_CGIBIN_ARIES_SESSIONCGI 1
#define CONFIG_CGIBIN_ARIES_CAPTCHACGI 1
#define CONFIG_CGIBIN_ARIES_HEDWIGCGI 1
#define CONFIG_CGIBIN_ARIES_PIGWIDGEONCGI 1
#define CONFIG_CGIBIN_ARIES_SERVICECGI 1
#define CONFIG_CGIBIN_ARIES_CONNTRACKCGI 1
#define CONFIG_CGIBIN_ARIES_FILELOAD 1
#define CONFIG_CGIBIN_ARIES_DLCONFIG_FILE "config.bin"
#define CONFIG_CGIBIN_ARIES_FILELOAD_MAXCODESIZE 0x100000
#define CONFIG_CGIBIN_ARIES_FWUPDATE_MAXCODESIZE 0xFB0000
#define CONFIG_CGIBIN_ARIES_FWUPDATE_MTDBLOCK "/dev/mtdblock/1"
#define CONFIG_CGIBIN_ARIES_FWUPDATER 1
#define CONFIG_CGIBIN_ARIES_HNAP 1
#define CONFIG_CGIBIN_ARIES_HNAP_UI 1
#undef  CONFIG_CGIBIN_ARIES_BRIDGE_WITHOUT_WIZARD

/* UPnP components */
#define CONFIG_CGIBIN_ARIES_SSDPCGI 1
#define CONFIG_CGIBIN_ARIES_SOAPCGI 1
#define CONFIG_CGIBIN_ARIES_GENACGI 1
#define CONFIG_CGIBIN_ARIES_WFADEV 1
#define CONFIG_CGIBIN_ARIES_WFANOTIFY 1
#define CONFIG_CGIBIN_ARIES_SCANDIR 1
#undef  CONFIG_CGIBIN_ARIES_PROXYCONNECT
#undef  CONFIG_CGIBIN_ARIES_REMOTE_LOGIN_ENCRYPTION
#define ELBOX_PROGS_PRIV_UPNP_AV 1
#define ELBOX_PROGS_PRIV_VERIFICATION_CODE 1
#undef  ELBOX_PROGS_PRIV_CLONED
#define ELBOX_PROGS_PRIV_LOGD 1
#undef  ELBOX_PROGS_PRIV_LOGD_AP
#define CONFIG_LOGD_PHP_HELPER "/etc/services/LOG/logd_helper.php"
#define CONFIG_LOGD_KLOG_INF_TABLE_SIZE 8
#undef  ELBOX_PROGS_PRIV_IODATA_QUICKCOPY
#undef  ELBOX_PROGS_PRIV_IODATA_QUICKCOPY_CLIENT
#define ELBOX_PROGS_PRIV_DDNSD 1
#undef  ELBOX_PROGS_PRIV_DDNSD_RELOAD_RESOLV_CONF
#define ELBOX_PROGS_PRIV_DDNSD_HELPER "/etc/scripts/ddnsd_helper.sh"
#undef  ELBOX_PROGS_PRIV_DDNS_SPEC_DEFAULT
#define ELBOX_PROGS_PRIV_DDNS_SPEC_VER_1_09 1
#undef  ELBOX_PROGS_PRIV_DDPD
#undef  ELBOX_PROGS_PRIV_DHCPPLUS
#undef  ELBOX_PROGS_PRIV_STARSPEED
#undef  ELBOX_PROGS_PRIV_TRAP_MONITOR
#undef  ELBOX_PROGS_PRIV_CAPTIVAL_PORTAL
#undef  ELBOX_PROGS_PRIV_ALPHA_BRIDGE
#undef  ELBOX_PROGS_PRIV_SOFTWARE_CONTROL
#undef  ELBOX_PROGS_PRIV_AUTOREKEY
#undef  ELBOX_PROGS_PRIV_ALPHA_3GTOOL
#undef  ELBOX_PROGS_PRIV_WEBREDIRECT
#undef  ELBOX_PROGS_PRIV_DHCP_BC2UC
#undef  ELBOX_PROGS_PRIV_WFI_INV
#undef  ELBOX_PROGS_PRIV_IGMP_2_6_27
#undef  ELBOX_PROGS_PRIV_USBOVERIP
#undef  ELBOX_PROGS_PRIV_RALINK_REPEATER
#undef  ELBOX_PROGS_PRIV_RALINK_SCAN
#define ELBOX_PROGS_PRIV_LLMNRESP 1
#define ELBOX_PROGS_PRIV_NAMERESOLV 1
#undef  ELBOX_PROGS_PRIV_WEPCLIENTINFOPATCH
#undef  ELBOX_PROGS_PRIV_MADWIFI_AR724X
#define ELBOX_UPDATEWIFISTATS 1
#undef  ELBOX_PROGS_PRIV_UPDATEWIFISTATS_RALINK
#undef  ELBOX_PROGS_PRIV_UPDATEWIFISTATS_ATHEROS
#undef  ELBOX_PROGS_PRIV_UPDATEWIFISTATS_BROADCOM
#define ELBOX_PROGS_PRIV_UPDATEWIFISTATS_REALTEK 1
#undef  ELBOX_PROGS_PRIV_RTSTAD
#undef  PROGS_PRIV_WAPI_SECURITY_VERSION
#undef  PROGS_PRIV_ATHEROS_SECURITY_VERSION
#define ELBOX_PROGS_PRIV_HOSTAPD_WPS 1

/* Support Samsung Auto Provision */
#undef  ELBOX_PROGS_PRIV_SUPPORT_AUTO_PROVISION

/* Support RealTek RT8198 */
#define ELBOX_PROGS_PRIV_REALTEK_RT8198 1

/* Support detail log for hostapd */
#undef  ELBOX_PROGS_PRIV_AP_SYSLOG

/* Support WPS 2.0 */
#define ELBOX_PROGS_PRIV_WPS_2_0 1

/* Support WPA Supplicant v0.5.9 */
#undef  ELBOX_PROGS_PRIV_SUPPLICANT_0_5_9
#undef  ELBOX_PROGS_PRIV_WPS_MONITOR
#undef  ELBOX_PROGS_PRIV_REALTEK_WSCD
#undef  ELBOX_PROGS_PRIV_WIFI_5GFIRST
#undef  ELBOX_PROGS_PRIV_APMODULE_FOR_ZOOM_NETWORKS
#undef  ELBOX_PROGS_PRIV_APMODULE_FOR_WINHAP
#undef  ELBOX_UPDATESITESURVEY
#undef  ELBOX_BCM_WPS_PBC
#define ELBOX_PROGS_PRIV_USBMOUNT 1

/* USBMOUNT configuration */
#undef  ELBOX_PROGS_PRIV_USBMOUNT_USE_SERIAL_NUMBER
#define ELBOX_PROGS_PRIV_USBMOUNT_MNT_ROOT "/var/tmp/storage"
#define ELBOX_PROGS_PRIV_USBMOUNT_HELPER "/etc/scripts/usbmount_helper.sh"
#define ELBOX_PROGS_PRIV_SHAREPORT_PLUS 1
#undef  CONFIG_SHAREPORT_NO_SAMBA
#define CONFIG_SHAREPORT_WITH_SAMBA 1
#define ELBOX_PROGS_PRIV_ALPHA_STUNNEL 1
#define ELBOX_PROGS_PRIV_WEB_FILE_ACCESS 1
#undef  ELBOX_NO_PTHREAD_KEEP_CONNECTION
#undef  ELBOX_PROGS_PRIV_PLC
#define ELBOX_PROGS_PRIV_MYDLINKEVENTD 1

/* Mydlink log config */
#undef  ELBOX_MYDLINK_LOG
#define CONFIG_MYDLINKEVENTD_USOCK "/var/mydlinkeventd_usock"
#define ELBOX_PROGS_PRIV_ARPMONITOR 1
#undef  ELBOX_PROGS_PRIV_WMM_SOURCE
#undef  ELBOX_PROGS_PRIV_HY_BRIDGE
#undef  ELBOX_PROGS_PRIV_HY
#undef  ELBOX_PROGS_PRIV_LTE
#undef  ELBOX_PROGS_PRIV_TC_MONITOR
#define ELBOX_PROGS_PRIV_TR069 1
#undef  ELBOX_PROGS_PRIV_TR069_CLIENT
#undef  ELBOX_PROGS_PRIV_TR069_CLIENT_V3_DH
#define ELBOX_PROGS_PRIV_TR069_CLIENT_V3 1

/* Select features */
#define ELBOX_PROGS_PRIV_GENERAL_MULTI 1
#define ELBOX_PROGS_PRIV_LAN_INTERFACE_CFG_MULTI 1
#define ELBOX_PROGS_PRIV_WLAN_MULTI 1
#undef  ELBOX_PROGS_PRIV_WLAN_WMM_MULTI
#undef  ELBOX_PROGS_PRIV_WLAN_WPS_MULTI
#undef  ELBOX_PROGS_PRIV_LARGER2BRIDGING_MULTI
#undef  ELBOX_PROGS_PRIV_QOS_MULTI
#undef  ELBOX_PROGS_PRIV_TR104
#define ELBOX_PROGS_PRIV_TR111 1
#define ELBOX_PROGS_PRIV_TR143 1
#define ELBOX_PROGS_PRIV_TR069_VERSION 3
#define ELBOX_PROGS_PRIV_TR069_HELPER "/etc/scripts/tr069/tr069_helper.sh"
#define ELBOX_PROGS_PRIV_TR069_SYSYEM "/etc/scripts/tr069/tr069_system.sh"
#define ELBOX_PROGS_PRIV_TR069_PROFILE "/etc/services/TR069/tr069-profile.xml"
#define ELBOX_PROGS_PRIV_TR069_HOSTFILE "/etc/scripts/tr069/tr069_host.sh"
#undef  ELBOX_PROGS_PRIV_ECOS_BRIDGE
#undef  ELBOX_PROGS_PRIV_ECOS_IPFILTER
#undef  ELBOX_PROGS_PRIV_ECOS_CLI
#undef  ELBOX_PROGS_PRIV_ECOS_PROGS
#undef  ELBOX_PROGS_PRIV_ECOS_PPPOED
#undef  ELBOX_PROGS_PRIV_ECOS_PPTPD
#undef  ELBOX_PROGS_PRIV_ECOS_SYSLOGD
#undef  ELBOX_PROGS_PRIV_ECOS_TELNETD
#undef  ELBOX_PROGS_PRIV_RA305X_DRIVER_V_2_5_0_0
#undef  ELBOX_PROGS_PRIV_RNDIMAGE
#undef  ELBOX_PROGS_PRIV_WSCUPNPD
#undef  ELBOX_PROGS_PRIV_ECOS_RALINK_WATCHDOG
#define CONFIG_ENCRYPT_FW_ENABLE 1
#undef  ELBOX_PROGS_PRIV_OPENZWAVE_CONTROLLER

/* ------------------------ Driver ------------------------ --- */
#undef  ELBOX_PARAGON_SUPPORT

/* Common library configuration */
#define ELBOX_COMLIB_MEM_HELPER_DISABLE 1
